const data = {
    products:[
        {
            name: 'Telefon',
            path: '1',
            description: 'sdncweioncwpiec',
            category: 'Telefon',
            stock: '2',
            price:'3',
            image:'images/telefon1.jpg',
        },
        {
            name: 'Telefon',
            path: '2',
            description: 'sdncweioncwpiec',
            category: 'Telefon',
            stock: '2',
            price:'3',
            image:'images/telefon1.jpg',
        },      
        {
            name: 'Telefon',
            path: '3',
            description: 'sdncweioncwpiec',
            category: 'Telefon',
            stock: '2',
            price:'3',
            image:'images/telefon1.jpg',
        },
        {
            name: 'Telefon',
            path: '3',
            description: 'sdncweioncwpiec',
            category: 'Telefon',
            stock: '2',
            price:'3',
            image:'images/telefon1.jpg',
        },
        {
            name: 'Telefon',
            path: '3',
            description: 'sdncweioncwpiec',
            category: 'Telefon',
            stock: '2',
            price:'3',
            image:'images/telefon1.jpg',
        },
        {
            name: 'Telefon',
            path: '3',
            description: 'sdncweioncwpiec',
            category: 'Telefon',
            stock: '2',
            price:'3',
            image:'images/telefon1.jpg',
        },
        
    ],
}; export default data;