version: '3.4'

services:
  elefanti60front:
    image: elefanti60front
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
