import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export const getServerSideProps = async () => {

  const postsRes = await fetch("https://jsonplaceholder.typicode.com/posts");
  const postsData = await postsRes.json();
  return{
    props: {
      postsData,
    },
  };
}

export default function Home(props) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>

    </div>
  )
}


