import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SinglePost from '../components/SinglePost';

export const getServerSideProps = async () => {
   
  const https = require("https");
  const myUrl = 'https:/localhost:7277/api/products/';
  const agent = new https.Agent({
  rejectUnauthorized: false
   })
  const productsRes = await fetch('https:/localhost:7277/api/products/', { agent });
  const productsData = await productsRes.json();
  console.log(productsData);

  return{
    props: {
     productsData,
    },
  };
}

export default function Posts({ productsData }) {
  
  const allProducts = productsData.map((p) => (<div key = {p.id}><SinglePost 
    title = {p.title}  
    desc = {p.decsription}
    id = {p.id}/>
    </div>));

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {allProducts}
      </main>

    </div>
  )
}


