import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SinglePost from '../components/SinglePost';

export const getServerSideProps = async () => {

  const postsRes = await fetch("https://jsonplaceholder.typicode.com/posts");
  const postsData = await postsRes.json();
  console.log(postsData);

  return{
    props: {
     postsData,
    },
  };
}

export default function Posts({ postsData }) {
  
  const allPosts = postsData.map((p) => (<div key = {p.id}><SinglePost 
    title = {p.title}  
    desc = {p.body}
    id = {p.id}/>
    </div>));

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {allPosts}
      </main>

    </div>
  )
}


